import { generateKeyPairSync, randomBytes } from "node:crypto";
import { existsSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const serverDirectory = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const repositoryDirectory = resolve(serverDirectory, "..");
const serverEnvironmentPath = resolve(serverDirectory, ".env.local");
const clientEnvironmentPath = resolve(repositoryDirectory, "client", ".env.local");
const force = process.argv.includes("--force");

const { privateKey, publicKey } = generateKeyPairSync("ec", {
  namedCurve: "P-256",
  privateKeyEncoding: { type: "pkcs8", format: "pem" },
  publicKeyEncoding: { type: "spki", format: "pem" },
});

const serverEnvironment = [
  "# Generated by `pnpm setup:local`. Development use only.",
  "NODE_ENV=development",
  "LOG_LEVEL=info",
  "DATABASE_URL=postgresql://chronix:chronix_dev@localhost:5433/chronix_dev",
  "DB_POOL_MIN=2",
  "DB_POOL_MAX=10",
  "REDIS_URL=redis://localhost:6380",
  "API_PORT=3000",
  "CORS_ORIGIN=http://localhost:3001",
  `JWT_PRIVATE_KEY=${JSON.stringify(privateKey)}`,
  `JWT_PUBLIC_KEY=${JSON.stringify(publicKey)}`,
  `API_KEY_HMAC_SECRET=${randomBytes(32).toString("hex")}`,
  `APP_ENCRYPTION_KEY=${randomBytes(32).toString("base64")}`,
  "ARGON2_MEMORY_COST=65536",
  "SCHEDULER_TICK_MS=5000",
  "SCHEDULER_BATCH_SIZE=50",
  "LEASE_DURATION_MS=60000",
  "WORKER_CONCURRENCY=10",
  "WORKER_ROLE=executor",
  "",
].join("\n");

const clientEnvironment = [
  "# Generated by `pnpm setup:local`. Development use only.",
  "NEXT_PUBLIC_API_URL=http://localhost:3000",
  "",
].join("\n");

function writeEnvironment(path, contents) {
  if (existsSync(path) && !force) {
    console.log(`Keeping existing ${path}. Use --force to replace it.`);
    return;
  }
  writeFileSync(path, contents, { encoding: "utf8", mode: 0o600 });
  console.log(`Created ${path}.`);
}

writeEnvironment(serverEnvironmentPath, serverEnvironment);
writeEnvironment(clientEnvironmentPath, clientEnvironment);
